baseURL = 'https://mamonas.dev/'
enableRobotsTXT = true
languageCode = 'en-us'
title = 'Konstantinas Mamonas - Personal Blog'
theme = 'Syl'
author = "Konstantinas Mamonas"
keywords = "Konstantinas Mamonas, personal blog, software engineering, technology, programming"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

[languages]
  [languages.en]
    title = "mamonas.dev"
    languageName = "English"

    [languages.en.params.logo]
      logoText = "mamonas.dev"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories"
        weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false

[minify]
  minifyOutput = true
  disableCSS = false

[minify.tdewolff.html]
  keepWhitespace = false
  keepComments = false
